#设置端口号
server:
  port: 8762
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xingpenghui/Springcloud1807
          search-paths: SpringCloud_ConfigServer
        native:
          search-locations: dbconfig.properties
  profiles:
    active: native #配置本地化



